/**
 * @file include/eurorack_config.hpp
 * @brief Human-editable default configuration for Eurorack Framework.
 *
 * @details
 * This is the primary configuration file for users who do not want to modify
 * framework internals. Values are grouped by purpose and expressed in ordinary
 * volts, milliseconds, hertz, and microseconds.
 *
 * A consuming project may replace this file without modifying the library by
 * defining EURORACK_FRAMEWORK_CONFIG_FILE to another quoted header path.
 *
 * @author Axel Napolitano
 * @date 2026
 * @contact eurorack@skjt.de
 *
 * @copyright Copyright (c) 2026 Axel Napolitano
 *
 * @license PolyForm Noncommercial License 1.0.0
 *
 * SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
 *
 * @ingroup configuration
 */

#pragma once

#include <cstdint>

/**
 * @brief User-editable Eurorack operating assumptions.
 *
 * These values describe intended software operating ranges. They are not
 * absolute maximum ratings and do not replace electrical input protection,
 * output-current limiting, rail-aware analog design, or calibration.
 */
namespace eurorack_config {

/* --------------------------------------------------------------------------
 * ANALOG SIGNAL LEVELS
 * --------------------------------------------------------------------------
 *
 * Common Eurorack audio is approximately 10 V peak-to-peak, or -5 V to +5 V.
 * General modulation and CV sources vary considerably. The framework therefore
 * accepts a broader -10 V to +10 V CV input range by default, while generating
 * the more conservative -5 V to +5 V range unless a project overrides it.
 */

/** Inclusive minimum voltage expected at a protected general CV input. */
inline constexpr float CV_INPUT_MIN_VOLTS = -10.0F;

/** Inclusive maximum voltage expected at a protected general CV input. */
inline constexpr float CV_INPUT_MAX_VOLTS = 10.0F;

/** Inclusive minimum voltage generated by a general bipolar CV output. */
inline constexpr float CV_OUTPUT_MIN_VOLTS = -5.0F;

/** Inclusive maximum voltage generated by a general bipolar CV output. */
inline constexpr float CV_OUTPUT_MAX_VOLTS = 5.0F;

/** Inclusive minimum nominal audio voltage processed by the application. */
inline constexpr float AUDIO_MIN_VOLTS = -5.0F;

/** Inclusive maximum nominal audio voltage processed by the application. */
inline constexpr float AUDIO_MAX_VOLTS = 5.0F;

/* --------------------------------------------------------------------------
 * PITCH CONTROL VOLTAGE
 * --------------------------------------------------------------------------
 *
 * Eurorack pitch normally uses 1 V per octave. Absolute pitch voltage ranges are
 * module-dependent, so the defaults accept modest negative pitch CV and provide
 * ten positive octaves for pitch-oriented signal generation and processing.
 */

/** Inclusive minimum accepted pitch-CV voltage. */
inline constexpr float PITCH_INPUT_MIN_VOLTS = -5.0F;

/** Inclusive maximum accepted pitch-CV voltage. */
inline constexpr float PITCH_INPUT_MAX_VOLTS = 10.0F;

/** Inclusive minimum generated pitch-CV voltage. */
inline constexpr float PITCH_OUTPUT_MIN_VOLTS = 0.0F;

/** Inclusive maximum generated pitch-CV voltage. */
inline constexpr float PITCH_OUTPUT_MAX_VOLTS = 10.0F;

/** Pitch scaling in volts per octave. */
inline constexpr float PITCH_VOLTS_PER_OCTAVE = 1.0F;

/** Equal-tempered chromatic divisions per octave. */
inline constexpr std::uint16_t PITCH_STEPS_PER_OCTAVE = 12U;

/* --------------------------------------------------------------------------
 * GATE, TRIGGER, AND CLOCK SIGNALS
 * --------------------------------------------------------------------------
 *
 * Eurorack gates, triggers, and clocks are commonly 0 V / +5 V. Inputs vary
 * between manufacturers. The software default treats 1 V or less as definitely
 * low and 2 V or more as definitely high, leaving a deliberate undefined band.
 * Hardware intended for maximum interoperability should tolerate signals up to
 * the supply rails even when the software operating level is lower.
 */

/** Highest gate-input voltage guaranteed to be interpreted as low. */
inline constexpr float GATE_INPUT_LOW_MAX_VOLTS = 1.0F;

/** Lowest gate-input voltage guaranteed to be interpreted as high. */
inline constexpr float GATE_INPUT_HIGH_MIN_VOLTS = 2.0F;

/** Nominal logical-low gate, trigger, and clock output voltage. */
inline constexpr float GATE_OUTPUT_LOW_VOLTS = 0.0F;

/** Nominal logical-high gate, trigger, and clock output voltage. */
inline constexpr float GATE_OUTPUT_HIGH_VOLTS = 5.0F;

/** Default trigger pulse duration in milliseconds. */
inline constexpr std::uint32_t TRIGGER_PULSE_MILLISECONDS = 5U;

/* --------------------------------------------------------------------------
 * USER INTERACTION
 * -------------------------------------------------------------------------- */

/** Default mechanical pushbutton debounce interval in milliseconds. */
inline constexpr std::uint32_t BUTTON_DEBOUNCE_MILLISECONDS = 20U;

/** Default minimum duration of a long press in milliseconds. */
inline constexpr std::uint32_t LONG_PRESS_MILLISECONDS = 800U;

/** Maximum interval between presses for a double click in milliseconds. */
inline constexpr std::uint32_t DOUBLE_CLICK_MILLISECONDS = 300U;

/** Delay before a held control begins repeating, in milliseconds. */
inline constexpr std::uint32_t REPEAT_DELAY_MILLISECONDS = 500U;

/** Interval between repeated events after the repeat delay, in milliseconds. */
inline constexpr std::uint32_t REPEAT_INTERVAL_MILLISECONDS = 100U;

/* --------------------------------------------------------------------------
 * FIRMWARE, DISPLAY, AND SIMULATOR TIMING
 * -------------------------------------------------------------------------- */

/** Recommended control-processing frequency in hertz. */
inline constexpr std::uint32_t CONTROL_UPDATE_HERTZ = 1000U;

/** Recommended display or UI refresh frequency in hertz. */
inline constexpr std::uint32_t UI_REFRESH_HERTZ = 60U;

/** Deterministic simulator time step in microseconds. */
inline constexpr std::uint32_t SIMULATOR_STEP_MICROSECONDS = 1000U;

} // namespace eurorack_config
