#!/usr/bin/env python3
from pathlib import Path
from library_layout import discover_libraries

def main():
 root=Path(__file__).resolve().parents[1]; libs=discover_libraries(root); out=root/'docs/architecture/framework-map.md'
 lines=['# Framework Map','','This file is generated by `python tools/generate-framework-map.py`. Do not edit the generated graph manually.','','## Dependency graph','','```mermaid','flowchart LR']
 for name in sorted(libs): lines.append(f'    {name.replace("-","_")}["{name}"]')
 for name,lib in sorted(libs.items()):
  for dep in sorted(lib.dependencies): lines.append(f'    {name.replace("-","_")} --> {dep.replace("-","_")}')
 lines+=['```','','## Library catalogue','','| Library | Direct dependencies |','|---|---|']
 for name,lib in sorted(libs.items()): lines.append(f'| `{name}` | '+(', '.join(f'`{d}`' for d in lib.dependencies) or 'None')+' |')
 out.write_text('\n'.join(lines)+'\n',encoding='utf-8'); print(f'Generated {out.relative_to(root)} for {len(libs)} libraries.')
if __name__=='__main__': main()
