#!/usr/bin/env python3
"""Generate the concrete driver test matrix from hardware-doc metadata."""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
rows=[]
for p in sorted((ROOT/'libraries').glob('eurorack-driver-*/hardware-doc.json')):
    m=json.loads(p.read_text(encoding='utf-8'))
    rows.append((m['library'], ', '.join(m['hardware']), '<br>'.join(m['tests']), '<br>'.join(m['examples']), m['status']))
out=ROOT/'docs/architecture/driver-test-matrix.md'
out.write_text('# Driver test matrix\n\nThis file is generated by `tools/generate-driver-test-matrix.py`. Do not edit it manually.\n\n| Library | Hardware | Dedicated native suite | Executable example | Status |\n|---|---|---|---|---|\n' + ''.join(f'| `{a}` | {b} | `{c}` | `{d}` | {e} |\n' for a,b,c,d,e in rows), encoding='utf-8')
print(f'Generated {out.relative_to(ROOT)} for {len(rows)} concrete drivers.')
